require('plugins')
require('file-explorer')
require('mason-config')
require('golsp')
require('pylsp')
require('code-completion')
require('custom-keys')
require('debugging')
require('styling')
require('code-runner')
require('line_numbers')

